services:
  pythonapp:
    build:
      context: ./app
      dockerfile: Dockerfile
    depends_on:
      - dbscripts
    environment:
      - DB_URL=mysql://root:hej123@localhost:3306/dbkursen

  dbscripts:
    build:
      context: ./dbscripts
    restart: always
    environment:
      MYSQL_DATABASE: 'dbkursen'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
